[[constraint]]
  name = "github.com/containerd/containerd"
  version = "1.3.2"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.7.3"

[[constraint]]
  name = "github.com/openfaas/faas"
  version = "0.18.7"

[[constraint]]
  name = "github.com/openfaas/faas-provider"
  version = "0.13.3"

[[constraint]]
  name = "github.com/vishvananda/netlink"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/vishvananda/netns"

[prune]
  go-tests = true
  unused-packages = true
